---
- name: base-devel group
  pacman:
    name:
      - autoconf
      - automake
      - binutils
      - bison
      - fakeroot
      - file
      - findutils
      - flex
      - gawk
      - gcc
      - gettext
      - grep
      - groff
      - gzip
      - libtool
      - m4
      - make
      - pacman
      - patch
      - pkgconf
      - sed
      - sudo
      - texinfo
      - which
    state: present

- name: Access Control utilities (ACL)
  pacman:
    name: acl
    state: present

- name: git
  pacman:
    name: git
    state: present

- name: cmake
  pacman:
    name: cmake
    state: present
- name: cross-compilation tools (LLVM & clang)
  pacman:
    name:
      - llvm
      - lld
      - clang
    state: present
- name: QEMU (Quick EMUlator)
  pacman:
    name:
      - qemu
      - qemu-arch-extra
    state: present

- name: Bash & other shells
  pacman:
    name:
      - bash
      - bash-completion
      - dash
    state: present
