---
- name: Yay dependencies
  become: true
  pacman:
    name:
      - git
      - pacman
      - go
      - sudo
    state: present

- name: Yay AUR helper
  become: true
  become_user: '{{ aur_user.name }}'
  aur:
    name: yay

- name: Quality of Life software
  block:
    - name: CLI tools
      become: true
      pacman:
        name:
          - ripgrep
          - fzf
          - the_silver_searcher
          - exa
          - starship
        state: present
    - name: CLI tools (AUR)
      become: true
      become_user: '{{ aur_user.name }}'
      aur:
        name: scc

- name: Terminal (terminator)
  become: true
  pacman:
    name:
      - terminator
    state: present

- name: Pinyin keyboard (fcitx)
  become: true
  pacman:
    name:
      - fcitx
      - fcitx-configtool
      - libpinyin
      - fcitx-libpinyin
    state: present

- name: Fonts
  become: true
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
    state: present

- name: LaTeX (texlive)
  become: true
  pacman:
    name:
      - texlive-bin
      - texlive-core
      - texlive-langchinese
      - texlive-fontsextra
      - texlive-langextra
      - texlive-latexextra
    state: present
