---
- name: X-org server
  pacman:
    name:
      - xorg-server
      - xorg-server-common
      - xorg-xinit
      - xorg-xrandr
      - xorg-xev
      - xorg-setxkbmap
      - xorg-xgamma
      - xorg-xinput
      - mesa-demos
    state: present

- name: Window Manager (i3-gaps)
  pacman:
    name:
      - i3-gaps
      - i3status
      - i3blocks
      - i3lock
      - py3status
    state: present

- name: Display Manager (lightdm)
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
