---
# The first play
- hosts: all
  pre_tasks:
    - name: Update pacman cache
      become: true
      pacman:
        update_cache: true
      tags:
        - software
  roles:
    - role: users
      tags: users
    - role: software
      tags: software
    - role: config
      tags: config
