---
# The first play
- hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update pacman cache
      become: yes
      pacman:
        update_cache: yes
#  handlers:
#    - name: restart networkmanager
#      service: name=networkmanager state=restarted
  tasks:
    - block: # root block 1
      - name: User setup
        import_tasks: '{{ playbooks_dir }}/user.yml'
      - name: Install "essential" software
        import_tasks: '{{ playbooks_dir }}/essentials.yml'
        tags:
          - software
      become: yes
    - block: # User block 1
      - name: Config
        import_tasks: '{{ playbooks_dir }}/config.yml'
        tags:
          - config
      become: yes
      become_user: '{{ normal_user.name }}'
