---
# TODO: split these plays into multiple files

# Install the software I use
- name: User applications
  hosts: all
  gather_facts: no
  tasks:
    - name: Terminal (terminator) and shell prompt (starship)
      become: yes
      pacman:
        name:
          - terminator
          - starship
        state: present

    - name: Vim and its plugins
      become: yes
      pacman:
        name:
          - vi
          - gvim
          - vim-ale
          - vim-ansible
        state: present

- name: Grab OS project into home directory
  hosts: all
  tasks:
    - git:
        repo: 'https://github.com/Ytrewq13/YtrewqOS'
        dest: ~/YtrewqOS
