---
- name: Create symlinks for ~/.config directory (in the home directory)
  block:
    - name: Check if the file already exists
      stat:
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
      register: sym
    - name: Remove symlink destinations if they exist
      file:
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
        state: absent
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Create the symlinks
      file:
        src: '/home/{{ normal_user.name }}/.config/{{ item.src }}'
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
        state: link
