---
- name: Create a symlink in the home dir for files in the ~/.config directory
  block:
    - name: Check if the file already exists
      stat:
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
      register: sym
    - name: Remove symlink destination if it exists
      file:
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
        state: absent
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Create the symlink
      file:
        src: '/home/{{ normal_user.name }}/.config/{{ item.src }}'
        path: '/home/{{ normal_user.name }}/{{ item.dest }}'
        state: link
